### ISSUE TITLE
problem: difficult to monitor peak traffic periods

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#100]
problem: difficult to monitor peak traffic periods

There was a serious spike in traffic today (about 1500 unique users at any given time). We are well over 150k unique visitors a day now. I frantically deployed more servers and tweaked the load balancer thismorning to keep the site alive. 

I think it's time to start monitoring the traffic so that at least there are some metrics that can be observed and maybe do something about these peak traffic volumes before they cripple servers.

**Comment by jimkleine** [comment]
@gazhayes I assume you have this deployed to one of the cloud services, which means you might be using their load balancer, but an alternative could be [HAProxy](https://www.haproxy.org), which has a built-in stats page?
