### ISSUE TITLE
problem: need infinite scroll in store list

### ISSUE THREAD

**Issue by akatrodiya** [howlongistheline/howlongistheline.org#104]
problem: need infinite scroll in store list, as on page load (while no search), user is waiting until all data returned

Solution: we have to fetch records with pagination on scroll

**Comment by gazhayes** [comment]
Users don't need to see all the stores, only stores that are nearby. I've already limited this to 50 stores so the speed is ok. Infinite scroll doesn't help with anything because the issue is latency and DOM overloading.
