### ISSUE TITLE
feature request: api for line length

### ISSUE THREAD

**Issue by gurubobnz** [howlongistheline/howlongistheline.org#106]
Hi team,

I'm working on a web app to help people spend less time once inside the supermarket. I was thinking it would be great to be able to include the line length from within the app. I'm not familiar enough with meteor to be able to spot how the client talks to the server, but in its current state is there an endpoint that could be used to fetch this information over http?

Thanks :)

**Comment by gazhayes** [comment]
Hi Bob,

There's no API endpoint, but feel free to send a pull request to add one if you like. Meteor is basically just NodeJS.

Alternatively, depending on what you are doing exactly you could just add it as a new feature here and take advantage of the existing userbase.

**Comment by gurubobnz** [comment]
Thanks, I'll look into Meteor in the future and see if I can manage a PR, thanks for the response.

**Comment by gazhayes** [comment]
No worries, let me know if you need any help.
