### ISSUE TITLE
problem: FAQ page only has my details but there are now other contributors

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#107]
problem: FAQ page only has my details but there are now other contributors

solution: remove the links to my facebook etc and simply add a link to the AUTHORS file.

**Comment by jimkleine** [comment]
@gazhayes It looks like this was addressed in #118, but I don't have rights to close this issue.

**Comment by gazhayes** [comment]
@jimkleine you should now be able to close issues etc, could you try closing this one to make sure it works?

**Comment by jimkleine** [comment]
@gazhayes Done. Fixed by #118.
