### ISSUE TITLE
problem: Line numbers become less relevant over time

### ISSUE THREAD

**Issue by emjas92** [howlongistheline/howlongistheline.org#115]
The number of people in the line should be reset each night/morning, or even after few hours, as it's irrelevant how many people there were "2 days ago", "yesterday", or even a few hours ago.

The number should probably be reset at midnight, assuming the store is not open 24hrs.
I understand this is related to having store hours available, but having the numbers expire would be a good start.

**Comment by gazhayes** [comment]
Yeah I actually had it working this way before but changed the data structure, I'll put it back in.

**Comment by jimkleine** [comment]
@gazhayes There is a downside to expiring the queues: we can't as easily identify "orphaned"/duplicate locations. Also, seeing an "old" queue  might encourage users to either update the queue themselves (good), or encourage the store's staff to do so (better): I'm seeing some evidence of this with a small local specialty supermarket I added (they weren't initially updating the queue at all, but the updates are becoming more frequent).  There is no real improvement to the data quality by resetting the queues.  We also have stores in alternate time zones (#58).

**Comment by gazhayes** [comment]
Un-assigning myself from this, if anyone picks it up in the meantime, the simplest solution is to use synced cron: https://github.com/howlongistheline/howlongistheline.org/blob/bf642afb2432910c9b96ad31f29713b9521b327d/server/main.js#L7

**Comment by jimkleine** [comment]
@gazhayes Do you actually have a cron job currently running for this?

The reason that I am asking is that I'm seeing updates being posted at times when stores are closed and I'm not seeing any local stores with updates >6 hours ago.

**Comment by gazhayes** [comment]
Ah yeah this should be closed now
