### ISSUE TITLE
problem: line numbers are being sent as undefined to /editLine

### ISSUE THREAD

**Issue by olliechick** [howlongistheline/howlongistheline.org#125]
solution: fix the "Update/Confirm x are waiting in line" button to send the queue length the user has selected

**Comment by olliechick** [comment]
Currently, clicking the button opens the page https://howlongistheline.org/editLine?id=__storeid__&lineSize=undefined

**Comment by gazhayes** [comment]
oops. I'll fix this.

**Comment by jimkleine** [comment]
@gazhayes Not sure if this is related, but this store somehow has a "NaN" queue length:
![NaN Queue](https://user-images.githubusercontent.com/47098744/79062062-d8389600-7cea-11ea-8230-0bcb3b382305.png)

**Comment by gazhayes** [comment]
@jimkleine weird. Is that the only one you found?

**Comment by jimkleine** [comment]
It looks like we might have three current representations for a 0-length queue:
1.  NaN for really recent updates (which implies this was broken in a recent commit):
![Pak'nSave Clendon - NaN](https://user-images.githubusercontent.com/47098744/79064561-0673a100-7cfe-11ea-8d4e-c58cbcbf9133.png)
2. Zero (correct) for updates from ~24 hours ago:
![New World Papatoetoe - 0 People](https://user-images.githubusercontent.com/47098744/79064575-26a36000-7cfe-11ea-943d-ea1012d30953.png)
3. Null strings for updates from ~7 days ago (presumably from before the slider UI change):
![The Pantry - Null People](https://user-images.githubusercontent.com/47098744/79064592-4d619680-7cfe-11ea-9383-9e349fe49de5.png)

**Comment by jimkleine** [comment]
@gazhayes I have just refreshed my dev DB from the last dump (thanks :-) ) and run a query to see how many NaN's we have.  There are eight, all with tightly-clustered last update times.  
![Documents with line = NaN (8)](https://user-images.githubusercontent.com/47098744/79065755-bfd67480-7d06-11ea-814e-17571d772ca0.png)
What TZ are we using for the production DB (this seems off for UTC)?

**Comment by jimkleine** [comment]
@gazhayes TZ might be UTC after all; Pak'nSave Clendon was ~6 hours ago, so ~3-4pm NZST.

**Comment by gazhayes** [comment]
Yeah it's in UTC. 

I'm not sure why this is happening, worth keeping an eye on it. I'll push DB updates fairly regularly because they can serve as defacto backups.

**Comment by olliechick** [comment]
Looks like this was caused by #124 (where users were sent to /editLine with
?lineSize=undefined, so unless they moved the slider on that page, that is
what was sent to the DB) and was fixed by #126
