### ISSUE TITLE
problem: There are some typos in the codebase, which can reduce users' trust and/or hinder understanding

### ISSUE THREAD

**Issue by olliechick** [howlongistheline/howlongistheline.org#128]
solution: fix the typos

**Comment by olliechick** [comment]
"shop" and "store" are both used - "shop" appears to be used the most, so I'll change all instances of "store" to "shop" in user-facing strings

**Comment by jimkleine** [comment]
We do have international users now ...  The Oxford dictionary entry for "store" says:

North American: A shop of any size or kind.
British(1): A large shop selling different types of goods.
British(2): A shop selling basic necessities e.g. village store

**Comment by olliechick** [comment]
that's a good point, i hadn't considered i18n... perhaps we should use store then?

**Comment by gazhayes** [comment]
@olliechick since you are doing the change, it's up to you.

The pressure is on, I hope you make the right choice!
