### ISSUE TITLE
problem: slider doesn't work on mobile

### ISSUE THREAD

**Issue by olliechick** [howlongistheline/howlongistheline.org#140]
Solution: it currently just listens for mouse up events, but it needs to just for "finger up" or whatever events is generated when a user selects a number on a touchscreen

**Comment by olliechick** [comment]
Needs to be implemented on /nearne and /editLine

**Comment by olliechick** [comment]
I think it's `onTouchEnd`

**Comment by gazhayes** [comment]
You could also do it on the `change` event

**Comment by gazhayes** [comment]
`onChange={ function(event) {...`

**Comment by olliechick** [comment]
yeah, one option would be to use `onChange` - and then track the events `touchmove` and `mousemove`, but it fires for every increment so it gets laggy when you move the thumb quickly

**Comment by jimkleine** [comment]
@olliechick I'm no longer seeing max/min numbers on the slider. Is this intentional? (I am seeing tool tips and dynamic updates to the button, but I have no sense of scale for initial movements).
