### ISSUE TITLE
problem: when searching, location isn't taken into account

### ISSUE THREAD

**Issue by olliechick** [howlongistheline/howlongistheline.org#146]
This causes an issue, for example if someone searches "Countdown" it would be most useful to find Countdown stores near them, currently the top result is in Pukekohe (despite my location being Christchurch).

**Comment by jimkleine** [comment]
@olliechick I instinctively search by suburb, which then returns local stores.  You could also keep typing: "Countdown [store name]", to reduce the result set.  I think we may need to be careful not to exclude/frustrate potentially valid searches that we haven't [yet] anticipated.  Is this a user-reported issue?

**Comment by olliechick** [comment]
No, it's not a user-reported issue, it just occurred to me when searching
"Countdown" to see if there were still some without a proper address.

**Comment by jimkleine** [comment]
@olliechick I believe I have identified the problem with the database: see my last update to #133.  

The current ability of users to delete duplicates is actually compounding this problem.  I originally reviewed and corrected 333 locations, but by the time my updates were applied 101 of those locations had been deleted (presumably as duplicates).  There are now an additional 308 locations that need to be checked (some of which, at first glance, look to be reloads of members of the 101 "duplicates" set).

I hope we will have my first round of updates live in the morning, and I'll try to get the remaining locations checked asap.  I suggest you "pause" this issue until then, and we can see if it remains a problem.
