### ISSUE TITLE
problem: can't update line length on mobile

### ISSUE THREAD

**Issue by reidwicks** [howlongistheline/howlongistheline.org#155]
Using Firefox on Android I'm unable to update the line length. Hitting "update line length" does nothing, as if I'm clicking on a blank part of the page.

Not sure what info you might need, but more than happy to provide it.

**Comment by gazhayes** [comment]
Thanks @reidwicks. Found the problem, should be fixed soon.

**Comment by gazhayes** [comment]
@reidwicks can you try again now?

**Comment by jimkleine** [comment]
@reidwicks Just following this up to confirm that this issue can be closed.  Is this working for you now?

**Comment by reidwicks** [comment]
> @reidwicks Just following this up to confirm that this issue can be closed. Is this working for you now?

It now shows an "updating" bar, but it unfortunately doesn't go anywhere

**Comment by jimkleine** [comment]
@reidwicks Can I get a little more detail please in order to try to reproduce this:

1.  Which OS/browser versions?

2.  What was your Internet connectivity at the time (mobile data vs in-store WiFi etc)?

3.  Which store were you at (so that I can check that its location coordinates are reasonable)?  Did both of these update attempts occur at the same store?

4.  Where were you standing relative to the store entrance e.g. close to the entrance or at the end of a long line etc?

5.  Were you prompted to confirm that you were really at that store before the update attempt was made?

6.  Do you happen to have a screenshot available?

**Comment by reidwicks** [comment]
> @reidwicks Can I get a little more detail please in order to try to reproduce this:
> 
>     1. Which OS/browser versions?
> 
>     2. What was your Internet connectivity at the time (mobile data vs in-store WiFi etc)?
> 
>     3. Which store were you at (so that I can check that its location coordinates are reasonable)?  Did both of these update attempts occur at the same store?
> 
>     4. Where were you standing relative to the store entrance e.g. close to the entrance or at the end of a long line etc?
> 
>     5. Were you prompted to confirm that you were really at that store before the update attempt was made?
> 
>     6. Do you happen to have a screenshot available?

1. I'm using Firefox for Android, running Android 9, version PPOS29.114-134-10

2. experienced this issue on both wifi and then data.

3. New World Willis St

4. I've always updated within 10 metres of the store entrance.

5. I've never been prompted with this service to confirm whether I was really at the store.

6. I'll get one on my next trip.

**Comment by gazhayes** [comment]
@reidwicks also, if possible can you try with a different browser and see if anything is different (to narrow down if it's specific to firefox or not)

thanks!

**Comment by jimkleine** [comment]
@reidwicks @gazhayes I'm also using Firefox (68.7.0) on Android and I was able to process a confirmation just before 9:00pm tonight i.e. ~35 mins ago without any issues.

There was a noticeable delay (seconds, not minutes) between tapping the button and receiving the pop-up confirming the request had been processed, and the page then reloaded.

I don't recall there being any options in Firefox mobile around disallowing pop-ups, but I will have a closer look later.  I'll check the coordinates for that store at the same time.

**Comment by jimkleine** [comment]
@gazhayes I have just had a further look at this:

1.  I don't see any settings in Firefox Android for blocking pop-ups;

2.  Google Maps says our location data was slightly off for New World Willis St Metro.  The coordinates we had put the store at the corner of Willis and Boulcott Sts.  From that point to the store's actual location on Google Maps is ~140m in a straight line, so I would have expected the "are you really at this store prompt";

3.  I have updated our coordinates to match Google Maps for now.

@reidwicks Please let us know if this fixes the problem for you.

NB  When you are next at the store, if you drop a pin near your current location in the Google Maps app, it should display what your phone thinks is your current decimal latitude and longitude.  If you could note those down as well, that may prove useful if your issue isn't solved.

**Comment by jimkleine** [comment]
@reidwicks In the absence of an update, I'm assuming this is working for you now.
