### ISSUE TITLE
problem: confirm button doesn't work sometimes

### ISSUE THREAD

**Issue by olliechick** [howlongistheline/howlongistheline.org#159]
See https://www.facebook.com/groups/1161156860891990/permalink/1169677936706549/

"I’ve noticed that whenever I try to drag the slider to update my local supermarket the slider moves but when I push confirm it just remains the same as it was before. the status doesn’t actually change. Why is that?"

**Comment by olliechick** [comment]
Might be related to #155

**Comment by gazhayes** [comment]
Could be related to #161

**Comment by ioioio8888** [comment]
I think it is already fixed by adding the loading indicator.
