### ISSUE TITLE
Problem: contributors can't profit from their work

### ISSUE THREAD

**Issue by sparcasticus** [howlongistheline/howlongistheline.org#160]
Problem: contributors can't profit from their work

Solution: adopt the [FIDO protocol](https://github.com/fidozero/documentation/blob/master/howlongistheline.MD)

### How to start
1. Read the protocol description linked above and ask questions about anything which doesn't make sense.
2. Start logging pull requests (including past pull requests). The FIDO protocol is currently being implemented so things are a bit clunky till launch. Contributors (listed in the authors file) have been sent a link to a shared spreadsheet where they can log their pull requests as well as associated hours and hourly rate. Send the link to any new people who contribute to the project.
3. Vote on pull requests. Vote yes if _all_ of the following are true:
a) Is this is a valid patch under the C4? 
b) Is this problem worth solving? 
c) Is this the simplest solution to the problem?
d) Is hourly rate and the amount of time spent reasonable?

4. If the vote passes simple majority, the contributor is credited with FUSD which will be issued on the FIDO chain once implementation work is complete. To see what FUSD is and how it works please see the protocol description above.

5. Identify and solve problems that will continue to be relevant after the lockdown.

**Comment by gazhayes** [comment]
I've started adding my pull requests.

**Comment by jimkleine** [comment]
@sparcasticus   Welcome to GitHub.  Perhaps you would like to start by introducing yourself, especially since you have no personal information in your profile?

@gazhayes "FUSD" seems to be a seldom used cryptocurrency called "Foton USD" that almost never trades and is (literally) only worth fractions of a penny when it does.  We seem to be the first and only GitHub project to ever be invited to this innovation.  Am I missing something?

**Comment by gazhayes** [comment]
I'm aware of the project. FUSD, FBTC, FNZD etc are assets on the proposed FIDO chain (they don't exist yet).

**Comment by jimkleine** [comment]
@gazhayes A Google search for those acronyms turns up nothing useful.

1.  Do you have an external/independent link?

2.  Is this really an issue for **this** project if it doesn't exist yet?

3.  Is it compatible with this project's licence?

**Comment by gazhayes** [comment]
@jimkleine have a careful read of the protocol description, once you see how it all fits together I think the role of F assets will become clear. I've been talking about it with @sparcasticus on and off for about a year so it's difficult to see which parts need further explanation for fresh eyes.

The protocol can start being _used_ now. Whether or not howlongistheline evolves into something useful after the lockdown is the real question in my mind, but I think that's at least more likely if contributors at least have an avenue to financial gain if it does.

Yes, actually this license is perfect for it. Contributors who want to participate can, and those who don't are not affected. The protocol itself is also under the same license for the same reasons as this one is (forking and enforced reusability).
