### ISSUE TITLE
problem: not easy to see which store is where

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#171]
problem: not easy to see which store is where. There are addresses, but not everyone knows the address of their local stores.

solution: simplest solution is probably to add a map tile from the existing [map server](https://github.com/howlongistheline/mapserver).

**Comment by jimkleine** [comment]
@gazhayes Is this a user-reported issue?  This could generate a significant amount of extra mobile data usage (I think, when I sampled this, map tiles were around 70Kb each?).

It is also potentially going to increase the amount of required vertical scrolling to find a store.

**Comment by gazhayes** [comment]
yeah user reported, also annoying for me anyway.

Those problems can be solved by putting it in a modal so that the tiles aren't fetched until the user actually clicks on the address.

**Comment by jimkleine** [comment]
@gazhayes Any solution to this should consider, but not necessarily implement, a method for "caching" the map tile for the store.

The tile is small enough to consider storing it directly in the store document, but large enough that we don't want to be passing it around unnecessarily.
