### ISSUE TITLE
problem: location data is sometimes up to 1km off

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#172]
problem: location data is sometimes up to 1km off

solution: implement https://github.com/gregsramblings/getAccurateCurrentPosition to replace geolocation.getCurrentPosition() with low accuracy enabled (high accuracy was disabled because it creates huge delays on some browsers)

**Comment by jimkleine** [comment]
@gazhayes Do we have a concrete example of this? I did perform some physical testing on an Android device (#84) that suggested accuracy should be acceptable.
