### ISSUE TITLE
problem: Stock Status wording layout issues

### ISSUE THREAD

**Issue by tel77** [howlongistheline/howlongistheline.org#194]
On wide screens (e.g. phone in landscape orientation) the stock status age of last update runs into the wording to the left of it, e.g. here:
https://howlongistheline.org/stocks?id=L7Pqn5iCK8wLtHruP 
"burger buns is out of stocka day ago".
No gap between "stock" and "a".

See screen shots attached: Portrait looks OK, landscape doesn't.

![Screenshot_20200424_landscape](https://user-images.githubusercontent.com/63988540/80153291-58c39480-8611-11ea-96bc-86705846338c.jpg)
![Screenshot_20200424_portrait](https://user-images.githubusercontent.com/63988540/80153299-5a8d5800-8611-11ea-8035-b4f49f31b0d7.jpg)

Please also test on a PC screen, with different window sizes and zoom levels, and you'll probably see the "a day ago" wording isn't in line with the similar words below it.

**Comment by jimkleine** [comment]
I can see how this was missed: it appears to be an artifact of the styling/theming of the OnsenUI components that only appears on the Android platform.  The other platforms (desktop, iOS) don't exhibit this problem.  I'll take a look at it.
