### ISSUE TITLE
problem: people still adding duplicate stores

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#48]
problem: people still adding duplicate stores

solution: when adding a new store, automatically search existing stores as the user types, and display it to the user.

**Comment by jimkleine** [comment]
@gazhayes A few thoughts on this issue:
1.  The current add procedure leaves store descriptions mostly as "free form" text i.e. not much standardisation.  I would be happy to spend some time "grooming" the database, but we probably need to agree a preferred format first.
2.  I could compile a list of all of the major NZ supermarkets (Countdown/PakNSave/New World) and we could bulk add them in advance.
3.  I note the comment in the FAQ re "why do I physically have to be at the store"?  I'm aware this is to geotag the store, but I do have some experience with OpenStreetMap data.  What are the "non-free" solutions you have considered?
4. Related to (3): The geotags themselves might help to prevent duplicates i.e. check the location, not the store name.

As an aside, stores that shouldn't currently be open have been added e.g. "Sagun Cafe & Indian Restaurant" in Winton.

**Comment by gazhayes** [comment]
@jimkleine 
>  I do have some experience with OpenStreetMap data

I was looking at that today actually (I'm just really trying to avoid Google) and it looks like it would do the trick but I don't have time to work out the API etc. If you wanted to do something there that would be most welcome!

I noticed that after I put an extra note on the add store page asking for people to search for existing listing before adding a new one, the number of duplicates being added dropped off significantly.

**Comment by jimkleine** [comment]
If that is the case, it might be enough for now to allow users to flag duplicates (#49) and just manually patrol anything that gets flagged (I don't yet have a feel for how well-behaved the site's users are being, but that might deteriorate as the number of users rise: I found the project via the NZ Herald article).

**Comment by jimkleine** [comment]
We still seem to be getting a number of (local to me) duplicates.  PaK N Save Mangere currently has three records.  One seems to be being kept updated, while one is falling into disuse and the other is a hybrid of Mangere and Ormiston (there is already an actual Pak N Save Ormiston).

I'm not sure if this is related to #51, but it would help if you could provide me with feedback on my last comment to that issue.

I'm currently taking a crash course in Meteor and setting up a MongoDB development environment, so I hope to begin contributing fixes soon.

**Comment by gazhayes** [comment]
> I don't yet have a feel for how well-behaved the site's users are being,

I haven't seen any malevolent behaviour so far, though I'm quite sure the trolls/vandals will come at some point.

> while one is falling into disuse

I think we can use this as a metric somehow for duplicate removal in combination with flagging. I noticed a few more today too.

> I'm currently taking a crash course in Meteor and setting up a MongoDB development environment, so I hope to begin contributing fixes soon.

That is excellent news! 

I'll get back to you on that other issue.
