### ISSUE TITLE
problem: Unable to update queue status when actually at the store: "Are you really at this store?"

### ISSUE THREAD

**Issue by jimkleine** [howlongistheline/howlongistheline.org#51]
I visited 4 local supermarkets (I'm a cyclist) this afternoon to update queues, add new stores and hand out posters to the door security staff.  Using Firefox on Android.  I was able to add two stores without issue (GetFresh Mangere and Countdown Mangere Town Centre), but I was refused access to update the queue status at the two existing stores (Pak n Save Mangere and Countdown Auckland Airport) "Are you really at this store?". I recorded decimal GPS locations for each of the two stores so that we can identify whether this is a bad data or a location logic problem:
1.  Pak N Save Mangere: -36.96827783, 174.79745184
2.  Countdown Auckland Airport: -36.99765505, 174.78860649

**Comment by gazhayes** [comment]
It's quite likely that whoever added those stores did so from somewhere else so the wrong coordinates are probably in the database.

The way I was thinking about dealing with this was to use openmaps to render an image with a map showing a pin on the current location and letting people reset it to their existing location if it's wrong.

However if you wanted to solve this in some other way that's also cool.

**Comment by jimkleine** [comment]
@gazhayes Can you check the store co-ordinates I supplied please (I was standing just in front of the main store entrance for each position measurement) to see whether it is a data problem?

Also, if you could supply me with the existing co-ords, it would allow me to desk check the logic in the distance function in lines.js.  I think you mirrored the code from here: https://www.geodatasource.com/developers/javascript, so it would probably be good to add the original comment headers and licence details (there are some "magic" variables and constants - I immediately recognised the 1.6x conversion from miles to kilometres, but 0.8684 and "N" didn't ring any bells - nautical miles it turns out)

**Comment by gazhayes** [comment]
I'll do a mongo dump so that you have the whole dataset. Will update this issue and the Readme too when it's done

**Comment by jimkleine** [comment]
> I'll do a mongo dump so that you have the whole dataset. Will update this issue and the Readme too when it's done

That would be a big help.  I did contemplate asking earlier, but I'm mindful that I'm "new" here and I didn't want too seem "demanding" until we have built a rapport.

In the meantime, I'm endeavouring to follow the project's C4 guidelines etc.  Feel free to let me know if/when I haven't got it quite right (I noticed that you edited one of the issue titles for style, for example).

**Comment by gazhayes** [comment]
@jimkleine I just pushed the current mongo dump and updated the instructions in the readme (https://github.com/gazhayes/howlongistheline.org#insert-the-database-if-running-locally-never-for-production)

>  I'm "new" here and I didn't want too seem "demanding" 

You're perfectly welcome here! Don't hesitate to ask for whatever you need :)

> I noticed that you edited one of the issue titles for style, for example

It can take a bit of getting used to, but try and think of things in term of problem/solution (even new features etc). The general idea is to log a *problem* as best you can and then (it's usually not clear at first) and then after some back and forth between participants you'll often want to refine it. I quite often reword my own issues after seeing other people's responses. In a perfect world the discussion naturally centres on the problem until it's refined so wall that the simplest possible solution becomes self-evident.

**Comment by gazhayes** [comment]
Depending on whether or not there's also some logic errors, #57 might make this redundant.

**Comment by jimkleine** [comment]
This behaviour has since been fixed: Users are currently prompted to update the store location (with a warning) if they try to update the queue at a store where there is a location mismatch.
