### ISSUE TITLE
enhancement: Reconsider text of line state labels

### ISSUE THREAD

**Issue by jimkleine** [howlongistheline/howlongistheline.org#53]
1.  One class of people best placed to keep the line status regularly updated is the door security folks, however the current "busy" status of "Busy. Stay Home." might not be acceptable for store staff to select (the "Stay Home" part).
2.  While trying to update line statuses today, I was offered two different criteria at two different stores (one said more than six; the other said more than 20).  We should be clear how long the queue potentially is for people, so they can make an informed decision about whether they will wait e.g. Busy (>6) or Busy (>20), or even a fourth status of Very Busy (>20) (much beyond this gets difficult to count with a queue that may be moving).
3.  This factors into the store "size" problem.  Of the two similar-sized queues at two supermarkets I observed this afternoon, one was moving significantly faster than the other.  Curiously, the faster moving queue was at the smaller of the two stores.  The critical element for shoppers is how long the wait time is, not necessarily the number of people in the queue, but we are currently using the latter as a proxy for the former.

**Comment by gazhayes** [comment]
@jimkleine I've started playing around with a solution to this actually:

<img width="1041" alt="Screenshot 2020-04-04 at 11 24 04 PM" src="https://user-images.githubusercontent.com/8143945/78424648-70bb8e80-76cb-11ea-8300-760478a04e25.png">

Basically: track the max number of people allowed in the store, and the number of people in the line. I'm not sure if a slider is the best way or if radio buttons should be used (but a bit more granular choices), what do you think?

**Comment by jimkleine** [comment]
I like the idea of the slider.  Some stores may tell you how many they allow inside at once e.g. for GetFresh (very small local store) it is 3, but many don't (none of the PaknSave/Countdowns I visited today did).
Specific implementation thoughts:
1.  You currently have no way to edit the in-store quantity;
2.  If the number of customers in store isn't known, a more useful proxy might be how "fast" the line is moving, but still thinking about how best to represent that.
3.  In a later iteration, it might be possible to have the store manager "claim" the store and set some of those parameters (Google Maps does this for businesses).

**Comment by jimkleine** [comment]
This issue has effectively been superseded by:

a.  The slider UI change; and

b.  Issues #43 and #60.
