### ISSUE TITLE
problem: search bar UI looks like an error

### ISSUE THREAD

**Issue by jimkleine** [howlongistheline/howlongistheline.org#54]
1.  There is a typo in the "location" bar: "getting your location" should probably be "Getting your location ..."
2.  The Search bar shouldn't have a red background colour: red should be reserved for errors etc. 
I appreciate that this is to highlight the search bar, but coloured backgrounds in text boxes can also present contrast issues that result in a need to "invert" the text colour e.g. white on blue etc.  Would a coloured border be better?  Some look and feel examples here: https://mdbootstrap.com/docs/jquery/forms/search/

![Minor Home Screen Typos etc](https://user-images.githubusercontent.com/47098744/78451148-34def400-76e0-11ea-8c00-9e3f4ec06688.jpg)

**Comment by olliechick** [comment]
I can fix the typo

**Comment by olliechick** [comment]
I can also fix the search bar colour
