### ISSUE TITLE
problem: DOM is getting overloaded with too many objects

### ISSUE THREAD

**Issue by jimkleine** [howlongistheline/howlongistheline.org#62]
The search field is becoming laggy, even on relatively capable devices e.g. iPad Air.  Possibly related to:

1. An increasing number of stores in the DB vs the current Search bar behaviour of incrementally filtering candidates as you type (I'm seeing a lag in character display in the search bar); or

2. More client processing of live status updates during filtering (is the slider UI more intensive in this regard? Could status updates be deferred during active filtering?)

**Comment by gazhayes** [comment]
Might be fixed in https://github.com/gazhayes/howlongistheline.org/commit/0facc4dbb6395db04349edeb1dc9eb7fd12e1bbd

but needs testing

**Comment by gazhayes** [comment]
That worked but broke a lot of other stuff, reverted. 

The actual problem here is that the DOM is getting overloaded with too many objects. I'll filter mongodb server side by location before sending it to the client so that only local stores are sent by defaut.

**Comment by jimkleine** [comment]
That might be a problem if a user is checking the queue from home before heading to the store.

In the relational world, I might be tempted to use "top" to limit the number of results, **but** that doesn't work either when the search criterium is complete, because there could potentially be a reasonably large number of legitimate stores for the search location e.g.

Searching for "Mangere" currently returns seven results (of which two are duplicates), but I presume the actual problem is when the search criteria has only been partially typed and we are also getting Milford, Motueka, Manukau etc.

Are you using keypress events (I haven't had time to search the code yet)?  Can you insert e.g. a 10/20/50ms delay somehow?

**Comment by jimkleine** [comment]
Related to this, the Home page auto-populates with "random" stores if location services aren't enabled.  That populates the initial UI, but is unlikely to be useful data/bandwidth to the mobile device.

**Comment by jimkleine** [comment]
@gazhayes I looked at the above commit (mostly as a learning opportunity).  If I understand this correctly, limit is MongoDB's top.  The test data dump has 333 location documents.  Is there a pending problem when we reach 501 locations?

**Comment by gazhayes** [comment]
We can just increase that 500 to a larger number. But in reality, most browsers will grind to a halt by the time we get there.

That reminds me, I better get onto this issue quickly.

**Comment by jimkleine** [comment]
Possible MVP solution:  Don't populate store results until either:

1. We have location service data and can limit to local stores; or

2. We have at least three characters in the Search bar (this is a simpler criterium than delays, but performance seems acceptable from about this point).

**Comment by gazhayes** [comment]
This is solved in #79. /nearme uses a location filtered subscription instead of just sending everything to the client for the browser to sort out.

I'm intending to put /nearme as the default (/) route when some other things on it are tidied up.
