### ISSUE TITLE
problem: "Getting your location" pane doesn't auto-hide if location services are not available

### ISSUE THREAD

**Issue by jimkleine** [howlongistheline/howlongistheline.org#63]
If location services are not enabled (or the browser's Share location? Request is denied), a pop-up appears ("Cant get the location ..."; message is missing the apostrophe).  That behaviour is working correctly, but the animated "Getting your location" should hide itself at that point.

solution: Auto-hide "Getting your location" pane if location services are not available.

**Comment by jimkleine** [comment]
This is related to renderLoading() in imports/ui/Index.jsx.

@gazhayes I recognise this as React code, but it might be a candidate for refactoring at some point in the future (duplication + inline styling e.g. @olliechick had to make multiple edits to support #54)

**Comment by ioioio8888** [comment]
I can fix this
