### ISSUE TITLE
problem: not all members are public

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#72]
problem: not all members are public

This is a personal choice but it's usually a good idea for members of the github organisation public. It sets the tone for an open culture as more people start getting involved.

You can make yourself public by going to https://github.com/orgs/howlongistheline/people and changing the setting next to your name to public.

Anyone who contributes to the project should be invited to become a member of the organisation as it makes certain things easier (increased privileges etc). You can also see any pending invitations here: https://github.com/orgs/howlongistheline/people/pending_invitations

ping
@olliechick
@jimkleine 
@ioioio8888

**Comment by jimkleine** [comment]
Done.

1.  @gazhayes I think this may be recent housekeeping on your part (last hour) but, if invitations were sent out earlier, I have been having problems all day with GitHub e-mail: they have managed to get at least four of their outbound mail servers blacklisted on SORBS today, and my mail server isn't enthusiastic about that, which means GitHub has been nagging me every couple of hours to re-verify my e-mail address.  SORBS uses honeypots, so they are actually spamming.  I have logged a GitHub support issue to try to get that cleared up and I will try to identify their mail server IPs later and whitelist them.

2.  Not sure what happened to issues 64-71, unless this was related to creating your personal fork?

**Comment by gazhayes** [comment]
> 2\. Not sure what happened to issues 64-71, unless this was related to creating your personal fork?

Github issue numbers and pull request numbers are indexed together, so #71 (for example) is there but it's a pull request not an issue.

**Comment by jimkleine** [comment]
@gazhayes Thanks for the clarification: I hadn't noticed before.

**Comment by ioioio8888** [comment]
Changed
