### ISSUE TITLE
problem: other developers might not know about facebook group

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#77]
@jimkleine  @olliechick there is a group here: https://www.facebook.com/groups/1161156860891990/?fref=nf

Let me know if you join so I can add you as an admin.

**Comment by olliechick** [comment]
I've just joined

**Comment by gazhayes** [comment]
@olliechick made you an admin :)

**Comment by kideveloper612** [comment]
I also joined
