### ISSUE TITLE
problem: many coordinates are wrong

### ISSUE THREAD

**Issue by gazhayes** [howlongistheline/howlongistheline.org#84]
problem: many coordinates are wrong (added incorrectly). This prevents other users from updating the status.

solution: instead of the toaster notification, send users to a view with:

Error: are you really at this location? It appears that either you are not at the shop, or we have the wrong coordinates for the shop.

If you are not at this shop right now: ask your friends on facebook etc to update this shop for you whenever they go.

If you *are* at this shop right now, please tap to reset the location.

Set the coordinates to the users coordinates, and append the existing coordinates to historical data.

When checking the users location matches the store, check historical coordinates too, and if any are a match let them update it.

**Comment by jimkleine** [comment]
@gazhayes This "seemed" to happen to me last night at my local PaknSave.  When I investigated further, I could update the location from the end of the (long) line, but not near the store entrance i.e. someone had added the store from a position in the queue at a time when the store was busy.

suggested MVP:  Extend (double/triple?) the locality radius.

**Comment by jimkleine** [comment]
@ioioio8888 I'll desk check the existing locality radius algorithm later today (I have a long tape measure and a nearby park :-) )

**Comment by jimkleine** [comment]
@ioioio8888 I was able to check this today, and the distance() function accuracy looks OK (there are some minor variations that I attribute to device limitations, but they shouldn't be material).
[Distance Check.pdf](https://github.com/howlongistheline/howlongistheline.org/files/4464302/Distance.Check.pdf)
