### ISSUE TITLE
problem: project structure is difficult to understand

### ISSUE THREAD

**Issue by akatrodiya** [howlongistheline/howlongistheline.org#91]
Problem: project structure needs to improve
For example - in ui directory, pages and layout are in same directory.

Solution: we can update file structure and code structure to better understanding. also we can divide components in to separate files, so it can be reusable.
Also we can move client and server startup parts in imports.

**Comment by gazhayes** [comment]
I think this is ok for now, it's not causing any big problems. If you make new modules use a better structure but no need to fix the existing structure.
