### ISSUE TITLE
problem: line under search box is misplaced while scroll down

### ISSUE THREAD

**Issue by akatrodiya** [howlongistheline/howlongistheline.org#93]
problem: line under search box is misplaced while scroll down, as no need to stick border line for search box
![Screenshot 2020-04-08 at 6 20 21 PM](https://user-images.githubusercontent.com/15026463/78785963-a3b09b80-79c5-11ea-8d3a-42a774c20bf9.png)

Solution: set border to content instead of search box, so can't stick always while scrolling window

**Comment by jimkleine** [comment]
An alternate solution might be to give the Search div a background colour, so that it is no longer "transparent".  That would result in the store list scrolling "under" the search bar.

**Comment by jimkleine** [comment]
With Firefox and Chrome on Android, I'm just seeing a floating Search box (no border on the containing div) and that looks good visually.

**Comment by olliechick** [comment]
![Screenshot_20200409-204105](https://user-images.githubusercontent.com/6047072/78876299-3d9a4600-7aa3-11ea-9008-622b4b9245d7.png)

I see a very thin line (going through New World in the attached screenshot)

**Comment by jimkleine** [comment]
@olliechick I think we will find that there is something like a 1px border on the div and that just removing it (rather than my initial suggestion of giving the div a background) might be a good solution.

**Comment by akatrodiya** [comment]
i will fix it

**Comment by jimkleine** [comment]
@gazhayes This looks like it was fixed by #103, but I don't have rights to close it.
